### ISSUE TITLE
Webcam shaking

### ISSUE THREAD

**Issue by YubinXie** [ktaletsk/NCCV#2]
Thanks for your codes! It is very helpful.

The only problem I have is 'the shaking of the video'. When the previous image is cleaned and switches to the next frame, the output space will be empty first (occupied by the next cell), and then display the next image. The moving up and down of the next cell causing a shaking effect of the webcam. 

Do you have any suggestion to solve the problem?

**Comment by ktaletsk** [comment]
Thank you for interest in my project! I was finally able to play around with the code again and I found a way of updating IPython display object with a new image instead of creating new ones every loop iteration. In my experience, this eliminated all the shaking I could see. Please, take a look at the latest commit: https://github.com/ktaletsk/NCCV/commit/f23bc8a934119636b12bc621324b0335e01c4373 and let me know if that fixed it or we need to look further

**Comment by YubinXie** [comment]
Thanks! It works perfectly in Chrome but shakes in Safari. But I think it is good enough!
